create database softroniics;
show databases;
use softroniics;
drop database softroniics;
show databases;
create database softroniics;
use softroniics;
create table interns(id int auto_increment, name varchar(100), place varchar(100),primary key(id));
show tables;
describe interns;
alter table interns add stack varchar(50) after name;
alter table interns modify name varchar(50);
alter table interns rename to students;
describe students;
alter table students rename column stack to current_stack;
insert into students(name, current_stack, place) values ("Arun", "Mern", "Ucity"),  ("Akshay", "Mern", "Nilambur");
select * from students;
select name, current_stack, place from students;
set sql_safe_updates = 0;
update students set current_stack="Python" where id =1;
select * from students where place = "Ucity" and current_stack = "Python" and name = "Arun";
select * from students where place = "Nilambur" or current_stack = "Python" and name = "Akshay";
select distinct name, place from students;
